apiVersion: v1
kind: Pod
metadata:
  name: zongsoft
  labels:
    app: zongsoft
spec:
  containers:
    # Redis 容器配置
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
      env:
        - name: REDIS_USER
          value: program
        - name: REDIS_PASSWORD
          value: zongsoft.redis2025
      command: ["sh", "-c"]
      args:
        - |
          redis-server --requirepass $$REDIS_PASSWORD --user $$REDIS_USER on >$$REDIS_PASSWORD ~* &* +@all
          wait $(cat /var/run/redis/redis-server.pid)

    # MySQL 容器配置
    - name: mysql
      image: mysql:8.4.6
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_USER
          value: program
        - name: MYSQL_PASSWORD
          value: zongsoft.mysql2025
        - name: MYSQL_DATABASE
          value: zongsoft
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: "yes"
      volumeMounts:
        - name: administratives-sql
          mountPath: /docker-entrypoint-initdb.d/Administratives-China-Tables(mysql).sql
          subPath: Administratives-China-Tables(mysql).sql
        - name: security-sql
          mountPath: /docker-entrypoint-initdb.d/Zongsoft.Security-mysql.sql
          subPath: Zongsoft.Security-mysql.sql
      command: ["sh", "-c"]
      args:
        - |
          # 启动 MySQL
          exec docker-entrypoint.sh mysqld &
          MYSQL_PID=$!

          # 等待 MySQL 完全启动
          while ! mysqladmin ping -h 127.0.0.1 -u root --silent; do
            sleep 1
          done

          # 执行 SQL 脚本
          mysql -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/Administratives-China-Tables(mysql).sql
          mysql -u root -p$MYSQL_ROOT_PASSWORD < /docker-entrypoint-initdb.d/Zongsoft.Security-mysql.sql

          # 删除 SQL 脚本文件
          rm -f /docker-entrypoint-initdb.d/Administratives-China-Tables(mysql).sql
          rm -f /docker-entrypoint-initdb.d/Zongsoft.Security-mysql.sql

          # 等待 MySQL 进程
          wait $MYSQL_PID

  # 卷配置用于挂载 SQL 脚本
  volumes:
    - name: administratives-sql
      hostPath:
        path: /mnt/d/Zongsoft/administratives/database/Administratives-China-Tables(mysql).sql
        type: File
    - name: security-sql
      hostPath:
        path: /mnt/d/Zongsoft/framework/Zongsoft.Security/database/Zongsoft.Security-mysql.sql
        type: File
