apiVersion: v1
kind: Pod
metadata:
  name: zongsoft.redis
  labels:
    app: zongsoft
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
          hostPort: 6379
      env:
        - name: REDIS_PASSWORD
          value: "xxxxxx"
      command: ["redis-server"]
      args: ["--requirepass", "$(REDIS_PASSWORD)"]
