apiVersion: v1
kind: Pod
metadata:
  name: zongsoft.caching
  labels:
    app: zongsoft
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
          hostPort: 6379
      env:
        - name: REDIS_PASSWORD
          value: "xxxxxx"
      command: ["redis-server"]
      args:
        - "--bind"
        - "0.0.0.0"
        - "--requirepass"
        - "$(REDIS_PASSWORD)"
        - "--protected-mode"
        - "no"
