apiVersion: v1
kind: Pod
metadata:
  name: zongsoft
spec:
  containers:
    - name: host
      image: dotnet/sdk:10.0
      workingDir: /Zongsoft/hosting
      securityContext:
        privileged: true
      command: ["/bin/bash"]
      args:
        - "-c"
        - |
          apt-get update && apt-get install -y --no-install-recommends unzip net-tools redis-tools openssh-server systemd nginx
          apt-get clean && rm -rf /var/lib/apt/lists/*

          ln -sf /lib/systemd/systemd /sbin/init
          ln -sf /lib/systemd/systemd /bin/systemd

          ln -sf /Zongsoft/hosting/.deploy/default/systemd/zongsoft.web.service /etc/systemd/system/
          ln -sf /Zongsoft/hosting/.deploy/default/systemd/zongsoft.daemon.service /etc/systemd/system/
          ln -sf /Zongsoft/hosting/.deploy/default/nginx/zongsoft.web.conf /etc/nginx/conf.d/

          exec /sbin/init
      env:
        - name: http_proxy
          value: "http://172.24.96.1:1080"
        - name: https_proxy
          value: "http://172.24.96.1:1080"
        - name: no_proxy
          value: "localhost,127.0.0.1,10.89.1.0/24,zongsoft.io,zongsoft.data,zongsoft.caching"
      volumeMounts:
        - mountPath: /Zongsoft
          name: zongsoft-volume

  volumes:
    - name: zongsoft-volume
      hostPath:
        path: /mnt/d/Zongsoft
        type: Directory
