apiVersion: v1
kind: Pod
metadata:
  name: zongsoft
spec:
  containers:
    - name: host
      image: dotnet/sdk:10.0
      securityContext:
        privileged: true
      ports:
        - containerPort: 8080
          hostPort: 8080
        - containerPort: 7969
          hostPort: 7969
        - containerPort: 6379
          hostPort: 6379
      env:
        - name: container
          value: podman
        - name: SYSTEMD_IGNORE_CHROOT
          value: "1"
      command: ["/bin/bash"]
      args:
        - "-c"
        - |
          apt-get update && apt-get install -y --no-install-recommends wget unzip systemd nginx redis-server
          apt-get clean && rm -rf /var/lib/apt/lists/*

          ln -sf /lib/systemd/systemd /sbin/init
          ln -sf /lib/systemd/systemd /bin/systemd

          ln -sf /Zongsoft/hosting/.deploy/default/systemd/zongsoft.web.service /etc/systemd/system/
          ln -sf /Zongsoft/hosting/.deploy/default/systemd/zongsoft.daemon.service /etc/systemd/system/
          ln -sf /Zongsoft/hosting/.deploy/default/nginx/zongsoft.web.conf /etc/nginx/conf.d/

          sed -i 's/# requirepass foobared/requirepass xxxxxx/' /etc/redis/redis.conf
          sed -i 's/^bind 127.0.0.1 -::1$/bind 0.0.0.0 -::1/' /etc/redis/redis.conf
          sed -i 's/^protected-mode yes$/protected-mode no/' /etc/redis/redis.conf

          exec /sbin/init
          systemctl enable redis
      volumeMounts:
        - mountPath: /Zongsoft
          name: zongsoft-volume

  volumes:
    - name: zongsoft-volume
      hostPath:
        path: /mnt/d/Zongsoft
        type: Directory
