apiVersion: v1
kind: Pod
metadata:
  name: zongsoft.rustfs
  labels:
    app: zongsoft
spec:
  containers:
    - name: rustfs
      image: rustfs/rustfs:latest
      ports:
        - containerPort: 9000
          protocol: TCP
          hostPort: 9000
        - containerPort: 9001
          protocol: TCP
          hostPort: 9001
      env:
        - name: RUSTFS_CONSOLE_ENABLE
          value: "true"
        - name: RUSTFS_ACCESS_KEY
          value: "rustfsadmin"
        - name: RUSTFS_SECRET_KEY
          value: "rustfsadmin"
      volumeMounts:
        - name: rustfs-volume
          mountPath: /data

  volumes:
    - name: rustfs-volume
      hostPath:
        path: /mnt/d/Zongsoft/hosting/.attachments
        type: Directory
